{application,phoenix_pubsub_nats,
             [{applications,[kernel,stdlib,elixir,logger,jason,phoenix_pubsub,
                             gnat]},
              {description,"Phoenix PubSub adapter based on Nats"},
              {modules,['Elixir.Nats.Consumer',
                        'Elixir.Nats.ConsumerSupervisor',
                        'Elixir.Nats.NatsPubsub',
                        'Elixir.Nats.NatsPubsub.State',
                        'Elixir.Nats.Serializer',
                        'Elixir.Nats.Serializer.Json',
                        'Elixir.Nats.Serializer.Native',
                        'Elixir.PhoenixPubsubNats']},
              {registered,[]},
              {vsn,"0.2.1"}]}.
