---
apiVersion: spawn-eigr.io/v1
kind: ActorSystem
metadata:
  name: rebels-system
  namespace: default
spec:
  externalInvocation:
    enabled: "true"
    externalConnectorRef: invocation-connection-ref-secret
  statestore:
    type: Native