---
apiVersion: spawn-eigr.io/v1
kind: ActorHost
metadata:
  name: rebels
  namespace: default
  annotations:
    spawn-eigr.io/actor-system: rebels-system
spec:
  host:
    image: eigr/spawn-playground-starwars-rebels:1.0.0
    ports:
      - name: http
        containerPort: 8090
  autoscaler:
    max: 3
